[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    paulstoffregen/OneWire
    milesburton/DallasTemperature
